---
# Security configuration.
security_sudoers_passwordless:
  - pi

# Python configuration.
pip_package: python3-pip
pip_executable: pip3
docker_pip_executable: '{{ pip_executable }}'

docker_registry_url: 